### ISSUE TITLE
Tracking issue: proper cli interface

### ISSUE THREAD

**Issue by lundibundi** [metarhia/metadoc#2]
This needs basic cli with

- [ ] basic `--help`, `--version` options
- [ ] allow to specify resulting directory for the doc files
- [ ] ability to specify multiple files via cli
- [ ] adding header/footer to the resulting file (via both file and text)
    - [ ] `--header "Hello"`, `--footer "Hello"`
    - [ ] `--header-file ./header.md`, `--footer-file ./footer.md` 
- [ ] allow to split a doc-per-file where documentation for each 'file.js' will be put in a separate 'file.md' file.

Edit by @SemenchenkoVitaliy:

- [ ] write output to stdout by default
- [ ] allow links to custom types
- [ ] remove links for unused types
- [ ] default configuration will be stored in `.metadocrc` file.

(points are put in order of priority)
Feel free to mark points as resolved once finished.

/cc @tshemsedinov @belochub @nechaido
