### ISSUE TITLE
Tracking issue: generation fixes

### ISSUE THREAD

**Issue by lundibundi** [metarhia/metadoc#24]
- [x] Remove spaces and make `|` non-monospaces
- [x] Always add newline before md lists
- [x] don't wrap monospaces sequences in the middle (`very long text` -> must not be `very long \n text`)

/cc @belochub @SemenchenkoVitaliy
